### PR TITLE
Use proper client functions on handlePacket

### PR DESCRIPTION
**Pull request by cam72cam**
This should prevent the crash described in https://github.com/Lomeli12/SimpleCondenser/issues/4

~~Still won't save the knowledge properly for some reason~~ Tome is now kept

### CODE REVIEW

**Comment by cam72cam** [comment]
By using the SimpleNetworkWrapper, we don't have to deal with how to fetch the proper user, the method of which seems to vary based on if you are on the server or client.

**Comment by Lomeli12** [comment]
I just got home from vacation, so I'll review this once I've recovered from travel exhaustion, but I think this should be fine.

**Comment by cam72cam** [comment]
Cool, thanks.

BTW, I have been having a ton of fun with this mod :+1:

**Comment by cam72cam** [comment]
The only issue I have been able to find is a Shift+Click not updating the emc values correctly.  It appears to only give you a few items.  When you close and re-open the inventory, your inventory is full with the item and the EMC value has not changed.

I will probably try to address that in a different PR

**Pull request merged**
